name: Release

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Version tags"
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: pack for Station (@Silicon Valley)
        run: |
          cp -r . ../dist
          rm -rf ../dist/.git
          rm -rf ../dist/logs
          cp online.env ../dist/.env
          mkdir ../dist/db
          tar cvfz dist-wework-proxy.tar.gz -C ../dist/ .

      - name: Push to Earth (@Beijing)
        uses: nogsantos/scp-deploy@master
        with:
          src: dist-wework-proxy.tar.gz
          host: 123.206.7.228
          remote: /home/ubuntu/
          port: 22
          user: ubuntu
          key: ${{ secrets.SSH_KEY }}

      - name: Distribution
        uses: appleboy/ssh-action@master
        with:
          host: 123.206.7.228
          port: 22
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: rm -rf /data/wework-proxy && mkdir -p /data/wework-proxy/logs && cd /data/wework-proxy && tar xvfz /home/ubuntu/dist-wework-proxy.tar.gz && sudo supervisorctl reload
